services:
  - docker

language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - libcairo2-dev
    - libjpeg8-dev
    - libgif-dev
    - libpango1.0-dev
    - graphicsmagick
    - libjpeg-turbo-progs
    - inkscape

env:
  - CXX=g++-4.8
  - CC=gcc-4.8

before_install: "rm -f /home/travis/.npm/*.lock"

script: "npm run-script travis"

after_success: "<coverage/lcov.info ./node_modules/coveralls/bin/coveralls.js"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/da6c90cc3857ade1086c
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
